{% set name = "abinit" %}
{% set version = "9.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abinit/abinit/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1b981140cb837c22f037a5dc8ec9769c007517e972ba667396ee300e006f543d
  patches:
    - optim.patch

build:
  number: 2
  skip: true  # [win]

{% if mpi != 'nompi' %}
{% set mpi_prefix = "mpi_" + mpi %}
{% else %}
{% set mpi_prefix = "nompi" %}
{% endif %}

requirements:
  build:
    - m4
    - autoconf
    - automake
    - make
    - libtool
    - openmpi-mpifort  # [mpi == 'openmpi']
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ mpi }}
    - libblas
    - liblapack
    - libxc <5.0
    - zlib
    - _openmp_mutex  # [linux]
    # need to list libnetcdf and netcdf-fortran twice to get version
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - fftw
    - fftw * {{ mpi_prefix }}_*  # [mpi != 'nompi']
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*  # [mpi != 'nompi']
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*  # [mpi != 'nompi']
    - netcdf-fortran
    - netcdf-fortran * {{ mpi_prefix }}_*  # [mpi != 'nompi']
  run:
    - {{ mpi }}
    - libxc <5.0
    - fftw * {{ mpi_prefix }}_*  # [mpi != 'nompi']
    - hdf5 * {{ mpi_prefix }}_*  # [mpi != 'nompi']
    - libnetcdf * {{ mpi_prefix }}_*  # [mpi != 'nompi']
    - netcdf-fortran * {{ mpi_prefix }}_*  # [mpi != 'nompi']

test:
  files:
    - 01h.pspgth
    - tbase1_1.files
    - tbase1_1.in
  commands:
    - abinit -b
    - abinit tbase1_1.in

about:
  home: https://www.abinit.org
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: ABINIT is an atomic-scale simulation software suite.

  description: |
    ABINIT is a software suite to calculate the optical, mechanical,
    vibrational, and other observable properties of materials. Starting
    from the quantum equations of density functional theory, you can
    build up to advanced applications with perturbation theories based on
    DFT, and many-body Green's functions (GW and DMFT) ...
  doc_url: https://wiki.abinit.org/doku.php
  dev_url: https://github.com/abinit/abinit/

extra:
  recipe-maintainers:
    - jan-janssen
    - gmatteo
    - jmbeuken
