{% set name = "abinit" %}
{% set version = "9.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abinit/abinit/archive/{{ version }}.tar.gz
  sha256: fbea29f531f14f7a6c24c3103d362881995213a45077204a7eec84057b7bb6f5

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - m4
    - autoconf
    - automake
    - make
    - libtool 
    - openmpi-mpifort  # [mpi == 'openmpi']
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - hdf5
    - libnetcdf
    - netcdf-fortran
    - libxc
    - fftw
    - {{ mpi }}
    - libblas
    - liblapack
    - scalapack
  run:
    - hdf5
    - libnetcdf
    - netcdf-fortran
    - libxc
    - fftw
    - {{ mpi }}
    - scalapack

test:
  commands:
    - abinit --help
    - test -x ${PREFIX}/bin/anaddb
    - test -x ${PREFIX}/bin/mrgddb
    - mrgdv --help
    - test -x ${PREFIX}/bin/cut3d

about:
  home: https://www.abinit.org
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: ABINIT is an atomic-scale simulation software suite.

  description: |
    ABINIT is a software suite to calculate the optical, mechanical, 
    vibrational, and other observable properties of materials. Starting 
    from the quantum equations of density functional theory, you can 
    build up to advanced applications with perturbation theories based on 
    DFT, and many-body Green's functions (GW and DMFT) ...
  doc_url: https://wiki.abinit.org/doku.php
  dev_url: https://github.com/abinit/abinit/

extra:
  recipe-maintainers:
    - jan-janssen
